services:
  traefik:
    image: traefik:v3.1
    ports:
      - 80:80
      - 8080:8080
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=${COMPOSE_PROJECT_NAME}_rokku
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE=Host(`{{ index .Labels "rokku.domain"}}.rokku.local`)
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_LOG_LEVEL=info
      - TRAEFIK_LOG_NOCOLOR=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rokku


  rokku:
    image: rokku:latest
    ports:
      - 3000:3000
    environment:
      - ROKKU_DOCKER_NETWORK=${COMPOSE_PROJECT_NAME}_rokku
      - ROKKU_SOURCEDIRECTORY=/var/rokku/workspaces
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspaces:/var/rokku/workspaces
    networks:
      - rokku

networks:
  rokku:
    driver: bridge

volumes:
  workspaces:
