services:
  traefik:
    image: traefik:v3.1
    ports:
      - 80:80
      - 8080:8080
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_NETWORK=${COMPOSE_PROJECT_NAME}_cleverclown
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      - TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE=Host(`{{ index .Labels "cleverclown.domain"}}.clever.clown`)
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_LOG_LEVEL=info
      - TRAEFIK_LOG_NOCOLOR=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cleverclown


  clever-clown:
    image: cleverclown:latest
    ports:
      - 3000:3000
    environment:
      - CLEVERCLOWN_DOCKER_NETWORK=${COMPOSE_PROJECT_NAME}_cleverclown
      - CLEVERCLOWN_SOURCEDIRECTORY=/var/cleverclown/workspaces
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspaces:/var/cleverclown/workspaces
    networks:
      - cleverclown

networks:
  cleverclown:
    driver: bridge

volumes:
  workspaces:
