apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: default
spec:
  ports:
  - name: traefik
    port: 8080
    nodePort: 32000
    protocol: TCP
    targetPort: dashboard
  - name: web
    port: 80
    nodePort: 30080
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    nodePort: 30443
    protocol: TCP
    targetPort: websecure
  selector:
    app: traefik
  type: NodePort
