[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers.docker]
exposedByDefault = false
network = "rokku"
defaultRule = "Host(`{{ index .Labels \"rokku.domain\"}}.rokku.local`)"

[api]
  dashboard = true
  insecure = true

[log]
  level = "DEBUG"
  noColor = true