[entryPoints]
  [entryPoints.web]
    address = ":80"

[providers.docker]
exposedByDefault = false
network = "cleverclown"
defaultRule = "Host(`{{ index .Labels \"cleverclown.domain\"}}.clever.clown`)"

[api]
  dashboard = true
  insecure = true

[log]
  level = "DEBUG"
  noColor = true